id: P9FDCDE88
initial_creation_type: input
source_metadata:
  title: Chokling Tersar Series
  language: de
  description: 'Texts related to the Chokling Tersar (mchog gling gter gsar), the
    New Treasures of Chokgyur Lingpa (1829–1870):'
  volume:
    1c592aa0fa164a2abe711e43b3c4f654:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    83c07e130b8345dfa338c16d9d1e04dc:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    98008e08d66a4e9c80518851070a239a:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    da73df6f4fc5457581ec6ef8d25b8fb7:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    1ef8d07f0b914d93a828caaf88b6d281:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    c8c6b618bc914c1998eb9d3c19383981:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    89e4aa2bb302492da692860dc28b9d1d:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    60b4eba0cc474db58825e6b8ee6db7d7:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Commentaries
    ef9cd625cd40472c97574d3a5fb792a2:
      title: The Lament of Rudra
      parent: Confession
    7d4143c797f64c078c87611529a1e8ab:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    d2238d42c32b402cbef076210a8e8879:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Prayers
    c74f8386386e442298420bb6fae1e4fc:
      title: The Prayer in Six Vajra Lines
      parent: Prayers
    6066871a587e4b079734f92bfa343e3a:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Prayers
    eecb4217895048c09f6ab9627dedd6bc:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Prayers
    ee8ed861e8434b5baa9cb0f8104f745e:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    21e2cf55c010497c9d9ec673ea1afa6b:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    d41e3c7bd1bb42449dda53398ded09ac:
      title: Extremely Secret Unelaborate Daily Sādhana for the Heart Practice of
        the Great Demon-Slayer
      parent: Sādhanas
    7f99c1220142487b8aa30c32fb2f495f:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Sur Offering
    bf5b459cb7584aa2a7b9aeb1961a816f:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-03-01T03:13:53.991861'
last_modified_at: '2022-03-01T03:13:53.991864'
